export interface CsvTemplate {
  id: string
  name: string
  description: string
  headers: string[]
  sampleData: string[][]
}

export const CSV_TEMPLATES: CsvTemplate[] = [
  {
    id: "general",
    name: "汎用テンプレート",
    description: "あらゆる種類のESGデータに使用できる汎用テンプレート",
    headers: [
      "company_code",
      "site_code",
      "fiscal_year",
      "fiscal_period",
      "kpi_category",
      "kpi_name",
      "value",
      "unit",
      "source",
      "collection_date",
      "notes",
    ],
    sampleData: [
      [
        "JP001",
        "TOKYO-HQ",
        "2023",
        "Q1",
        "Energy",
        "Electricity",
        "12500",
        "kWh",
        "Utility Bill",
        "2023-03-31",
        "東京本社の電力使用量",
      ],
      [
        "JP001",
        "OSAKA-BR",
        "2023",
        "Q1",
        "Energy",
        "Gas",
        "450",
        "m3",
        "Utility Bill",
        "2023-03-31",
        "大阪支社のガス使用量",
      ],
      [
        "JP001",
        "NAGOYA-BR",
        "2023",
        "Q1",
        "Waste",
        "General Waste",
        "320",
        "kg",
        "Waste Report",
        "2023-03-31",
        "名古屋支社の一般廃棄物",
      ],
    ],
  },
  {
    id: "ghg",
    name: "GHG排出量テンプレート",
    description: "温室効果ガス排出量データ専用のテンプレート",
    headers: [
      "company_code",
      "site_code",
      "fiscal_year",
      "fiscal_period",
      "scope",
      "category",
      "activity_type",
      "activity_amount",
      "activity_unit",
      "emission_factor",
      "emission_factor_unit",
      "emissions",
      "emissions_unit",
      "source",
      "collection_date",
      "notes",
    ],
    sampleData: [
      [
        "JP001",
        "TOKYO-HQ",
        "2023",
        "Q1",
        "Scope 1",
        "Stationary Combustion",
        "Natural Gas",
        "1000",
        "m3",
        "2.1",
        "kg-CO2/m3",
        "2100",
        "kg-CO2e",
        "Utility Bill",
        "2023-03-31",
        "ボイラー用天然ガス",
      ],
      [
        "JP001",
        "TOKYO-HQ",
        "2023",
        "Q1",
        "Scope 2",
        "Purchased Electricity",
        "Grid Electricity",
        "5000",
        "kWh",
        "0.47",
        "kg-CO2/kWh",
        "2350",
        "kg-CO2e",
        "Utility Bill",
        "2023-03-31",
        "購入電力",
      ],
      [
        "JP001",
        "OSAKA-BR",
        "2023",
        "Q1",
        "Scope 3",
        "Business Travel",
        "Air Travel",
        "2000",
        "passenger-km",
        "0.12",
        "kg-CO2/passenger-km",
        "240",
        "kg-CO2e",
        "Travel Report",
        "2023-03-31",
        "出張による排出",
      ],
    ],
  },
  {
    id: "water",
    name: "水使用量テンプレート",
    description: "水使用量と排水データ専用のテンプレート",
    headers: [
      "company_code",
      "site_code",
      "fiscal_year",
      "fiscal_period",
      "water_type",
      "water_source",
      "water_destination",
      "water_quality",
      "water_stress_area",
      "consumption_amount",
      "consumption_unit",
      "source",
      "collection_date",
      "notes",
    ],
    sampleData: [
      [
        "JP001",
        "TOKYO-HQ",
        "2023",
        "Q1",
        "Fresh Water",
        "Municipal Supply",
        "Municipal Treatment",
        "Potable",
        "No",
        "1200",
        "m3",
        "Utility Bill",
        "2023-03-31",
        "上水道使用量",
      ],
      [
        "JP001",
        "OSAKA-BR",
        "2023",
        "Q1",
        "Fresh Water",
        "Municipal Supply",
        "Municipal Treatment",
        "Potable",
        "No",
        "800",
        "m3",
        "Utility Bill",
        "2023-03-31",
        "上水道使用量",
      ],
      [
        "JP001",
        "NAGOYA-BR",
        "2023",
        "Q1",
        "Recycled Water",
        "On-site Treatment",
        "Reuse",
        "Non-potable",
        "No",
        "150",
        "m3",
        "Internal Meter",
        "2023-03-31",
        "中水再利用量",
      ],
    ],
  },
  {
    id: "waste",
    name: "廃棄物テンプレート",
    description: "廃棄物データ専用のテンプレート",
    headers: [
      "company_code",
      "site_code",
      "fiscal_year",
      "fiscal_period",
      "waste_type",
      "waste_category",
      "hazardous",
      "disposal_method",
      "amount",
      "unit",
      "recycling_rate",
      "source",
      "collection_date",
      "notes",
    ],
    sampleData: [
      [
        "JP001",
        "TOKYO-HQ",
        "2023",
        "Q1",
        "Paper",
        "General Waste",
        "No",
        "Recycling",
        "500",
        "kg",
        "100",
        "Waste Report",
        "2023-03-31",
        "紙ごみリサイクル",
      ],
      [
        "JP001",
        "OSAKA-BR",
        "2023",
        "Q1",
        "Plastic",
        "General Waste",
        "No",
        "Incineration",
        "300",
        "kg",
        "0",
        "Waste Report",
        "2023-03-31",
        "プラスチックごみ",
      ],
      [
        "JP001",
        "NAGOYA-BR",
        "2023",
        "Q1",
        "Electronic Waste",
        "Industrial Waste",
        "Yes",
        "Specialized Treatment",
        "50",
        "kg",
        "80",
        "Manifest",
        "2023-03-31",
        "電子機器廃棄物",
      ],
    ],
  },
]

// CSVデータを生成する関数
export function generateCsvContent(template: CsvTemplate): string {
  // ヘッダー行
  let csvContent = template.headers.join(",") + "\n"

  // サンプルデータ行
  template.sampleData.forEach((row) => {
    csvContent += row.join(",") + "\n"
  })

  return csvContent
}

// テンプレートIDからテンプレートを取得する関数
export function getTemplateById(templateId: string): CsvTemplate | undefined {
  return CSV_TEMPLATES.find((template) => template.id === templateId)
}
